[project]
name = "toronto-beaches-ecoli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sean Murphy", email = "seandata8@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "polars>=1.44.2",
]

[project.scripts]
toronto-beaches-ecoli = "toronto_beaches_ecoli:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "contextily>=1.7.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
]
